defaults:
  - general

model_type: LogReg
params: 
  penalty: l2
  tol: 0.0001
  C: 1.0
  fit_intercept: True
  intercept_scaling: 1
  class_weight: ~
  random_state: ~
  solver: lbfgs
  max_iter: 100
  multi_class: auto
  verbose: 0
  warm_start: False
  n_jobs: ~
  l1_ratio: ~