apiVersion: v1
kind: Pod
metadata:
  name: online-inference
  labels:
    name: online-inference
spec:
  containers:
    - name: online-inference
      image: gotovtsev/ml_prod_2
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8000