apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probe
  labels:
    name: online-inference-probe
spec:
  containers:
    - name: online-inference-probe
      image: gotovtsev/ml_prod_2:v3
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8000
      
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 50
        periodSeconds: 10
        timeoutSeconds: 2

      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 1
        periodSeconds: 10

      
